// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiA1wXyqozyvrydS5mltcFJVLZULYLdg',
    appId: '1:722788472688:web:1355fd102fe8cb17c821b5',
    messagingSenderId: '722788472688',
    projectId: 'collabverse-21356',
    authDomain: 'collabverse-21356.firebaseapp.com',
    storageBucket: 'collabverse-21356.firebasestorage.app',
    measurementId: 'G-VG3T8Y3PKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmMI7c3SfF-1RVxSwgSB8EV8MSY9sD_ow',
    appId: '1:722788472688:android:542b64010326d1e4c821b5',
    messagingSenderId: '722788472688',
    projectId: 'collabverse-21356',
    storageBucket: 'collabverse-21356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fIQhD2_uexFB4niTCf66VUmK3XRnvOM',
    appId: '1:722788472688:ios:e97d07b001cc4471c821b5',
    messagingSenderId: '722788472688',
    projectId: 'collabverse-21356',
    storageBucket: 'collabverse-21356.firebasestorage.app',
    iosBundleId: 'com.example.collabverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_fIQhD2_uexFB4niTCf66VUmK3XRnvOM',
    appId: '1:722788472688:ios:e97d07b001cc4471c821b5',
    messagingSenderId: '722788472688',
    projectId: 'collabverse-21356',
    storageBucket: 'collabverse-21356.firebasestorage.app',
    iosBundleId: 'com.example.collabverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQiA1wXyqozyvrydS5mltcFJVLZULYLdg',
    appId: '1:722788472688:web:cae44be016378891c821b5',
    messagingSenderId: '722788472688',
    projectId: 'collabverse-21356',
    authDomain: 'collabverse-21356.firebaseapp.com',
    storageBucket: 'collabverse-21356.firebasestorage.app',
    measurementId: 'G-TLXKZWEPXS',
  );
}
